"""initial migration

Revision ID: 25792adc5e08
Revises:
Create Date: 2025-07-23 05:07:25.459417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25792adc5e08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agresor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('apellido', sa.String(length=64), nullable=True),
    sa.Column('dni', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('domicilio', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('reincidente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('victima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.Column('apellido', sa.String(length=64), nullable=True),
    sa.Column('dni', sa.String(length=10), nullable=True),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('domicilio', sa.String(length=128), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('causa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_causa', sa.String(length=64), nullable=True),
    sa.Column('tipo_causa', sa.String(length=64), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('victima_id', sa.Integer(), nullable=True),
    sa.Column('agresor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agresor_id'], ['agresor.id'], ),
    sa.ForeignKeyConstraint(['victima_id'], ['victima.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('causa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_causa_numero_causa'), ['numero_causa'], unique=True)

    op.create_table('camara_gesell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('causa_id', sa.Integer(), nullable=True),
    sa.Column('fecha_grabacion', sa.DateTime(), nullable=True),
    sa.Column('psicologo', sa.String(length=128), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['causa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pericia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('causa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_pericia', sa.String(length=64), nullable=True),
    sa.Column('fecha_pericia', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['causa_id'], ['causa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pericia')
    op.drop_table('camara_gesell')
    with op.batch_alter_table('causa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_causa_numero_causa'))

    op.drop_table('causa')
    op.drop_table('victima')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('agresor')
    # ### end Alembic commands ###
